// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfyhjjuuqjrdcimvbxec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeWhqanV1cWpyZGNpbXZieGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExMTQyODUsImV4cCI6MjA5NjY5MDI4NX0.6RdSrs_PJ2BcKKIk5iGU5K0_LYG48MEj2sN4EKZEV60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});