// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqpdurqabxcjprgguasl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcGR1cnFhYnhjanByZ2d1YXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTEwNzMsImV4cCI6MjA2Njg4NzA3M30.Rjf8alSgfiUfrhGF5sOEItdiS0x5eulYk818GPtJw0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});