// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pokunsfbywyzqaaxkbvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBva3Vuc2ZieXd5enFhYXhrYnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDgzMjAsImV4cCI6MjA2NzIyNDMyMH0.f3-16ENLnvmln1d2JVUdl7kShYrj6P2n4k9HPf7t9Rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});